In [1]:
import numpy as np
from gym import spaces
from gym.utils import seeding

import math
import matplotlib
import random
import matplotlib.pyplot as plt

import mayavi.mlab
from mayavi import mlab

float_dtype = np.float32
int_dtype = np.int32

In [7]:
x, y= np.mgrid[0.5:9.5:10j, 0.5:9.5:10j]
print(x.shape)

(10, 10)


In [8]:
print(x)

[[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
 [1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5]
 [2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]
 [3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5]
 [4.5 4.5 4.5 4.5 4.5 4.5 4.5 4.5 4.5 4.5]
 [5.5 5.5 5.5 5.5 5.5 5.5 5.5 5.5 5.5 5.5]
 [6.5 6.5 6.5 6.5 6.5 6.5 6.5 6.5 6.5 6.5]
 [7.5 7.5 7.5 7.5 7.5 7.5 7.5 7.5 7.5 7.5]
 [8.5 8.5 8.5 8.5 8.5 8.5 8.5 8.5 8.5 8.5]
 [9.5 9.5 9.5 9.5 9.5 9.5 9.5 9.5 9.5 9.5]]


In [9]:
print(y)

[[0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]]
